from enum import Enum


class SSH_Messages(Enum):
    INVALID = -1
    DEFAULT = 0
    SSH_AGENTC_REQUEST_IDENTITIES = 11
    SSH_AGENT_IDENTITIES_ANSWER = 12
    SSH_AGENT_FAILURE = 5
    SSH_AGENT_SUCCESS = 6
