[project]
name = "sshagent-py"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ganesh Tiwari", email = "ganesht049@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
sshagent-py = "sshagent_py:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ruff>=0.16.8",
]
